channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.17.1
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==6.1.0
  - scikit-learn==1.4.2
  - scipy==1.11.4
  - xgboost==2.1.2
name: mlflow-env
